--Justin Vodoor

--SCHEMA

CREATE SCHEMA RAD;

SELECT * INTO STU168DB.RAD.APARTMENT FROM STARTERDB.RAD.APARTMENT
SELECT * INTO STU168DB.RAD.DEPENDENT FROM STARTERDB.RAD.DEPENDENT
SELECT * INTO STU168DB.RAD.LEASE FROM STARTERDB.RAD.LEASE
SELECT * INTO STU168DB.RAD.RENTER FROM STARTERDB.RAD.RENTER



--1 - Querying renter information for leases starting in July 1st, 2021, but did not sign a lease in July 1st, 2022.

SELECT RAD.RENTER.RENTER_ID, CONCAT(RAD.RENTER.RENTER_FNAME, ' ', RAD.RENTER.RENTER_LNAME) AS "NAME", 
		RAD.RENTER.RENTER_PHONE AS "PHONE", RAD.APARTMENT.APART_NUM, RAD.APARTMENT.APART_BUILDING AS "BUILDING"
FROM RAD.RENTER
LEFT JOIN RAD.LEASE
ON RAD.RENTER.RENTER_ID = LEASE.RENTER_ID
LEFT JOIN RAD.APARTMENT
ON RAD.LEASE.APART_NUM = RAD.APARTMENT.APART_NUM
WHERE RAD.LEASE.LEASE_BEGIN = '2021-07-01' 
	AND RAD.LEASE.RENTER_ID NOT IN (
		SELECT RAD.LEASE.RENTER_ID
		FROM RAD.LEASE
		WHERE RAD.LEASE.LEASE_BEGIN = '2022-07-01')
	OR  RAD.APARTMENT.APART_NUM IS NULL 
ORDER BY RAD.RENTER.RENTER_LNAME, RAD.RENTER.RENTER_FNAME;

--2 - Querying Number of people per bedroom in each apartment for leases that end on June 30th, 2023. 
--    Number of people per bedroom is considered as tenant + dependents / number of bedrooms.

SELECT RAD.RENTER.RENTER_ID, RAD.RENTER.RENTER_LNAME, 
    (1 +  COUNT(RAD.DEPENDENT.RENTER_ID) ) / RAD.APARTMENT.APART_BED AS "PEOPLE / BEDROOM"
FROM RAD.RENTER 
JOIN RAD.LEASE  
ON RAD.RENTER.RENTER_ID = RAD.LEASE.RENTER_ID
JOIN RAD.APARTMENT 
ON RAD.LEASE.APART_NUM = RAD.APARTMENT.APART_NUM
LEFT JOIN RAD.DEPENDENT
ON RAD.DEPENDENT.RENTER_ID = RAD.RENTER.RENTER_ID
WHERE RAD.LEASE.LEASE_END = '2023-06-30'
GROUP BY RAD.RENTER.RENTER_ID, Rad.RENTER.RENTER_LNAME, RAD.APARTMENT.APART_BED
ORDER BY "PEOPLE / BEDROOM" DESC, RAD.RENTER.RENTER_ID;


--3 - Display apartments that have never been rented to a renter with dependents in only Building's A and C.

SELECT RAD.APARTMENT.APART_NUM AS "APARTMENT", RAD.APARTMENT.APART_BUILDING AS "BUILDING", RAD.APARTMENT.APART_BED AS "BEDROOMS"
FROM RAD.APARTMENT
WHERE RAD.APARTMENT.APART_BUILDING IN ('A', 'C') 
	AND RAD.APARTMENT.APART_NUM NOT IN (
		SELECT RAD.LEASE.APART_NUM
		FROM RAD.LEASE
		JOIN RAD.RENTER 
		ON RAD.LEASE.RENTER_ID = RAD.RENTER.RENTER_ID
		JOIN RAD.DEPENDENT 
		ON RAD.RENTER.RENTER_ID = RAD.DEPENDENT.RENTER_ID )
ORDER BY RAD.APARTMENT.APART_BUILDING, RAD.APARTMENT.APART_NUM;													


--4 - Querying for all leases that either (started on Jul 1, 2022 and had sq ft > 1000) or (started on 7/1/21 and had either 
--    (sq ft > 900 AND rent < $1000) OR (sq ft > 1000 AND rent < $1100) )

SELECT RAD.RENTER.RENTER_ID, RAD.RENTER.RENTER_FNAME, RAD.RENTER.RENTER_LNAME, RAD.LEASE.LEASE_BEGIN, RAD.APARTMENT.APART_SQFT, RAD.LEASE.LEASE_RENT
FROM RAD.RENTER
JOIN RAD.LEASE
ON RAD.LEASE.RENTER_ID = RAD.RENTER.RENTER_ID
JOIN RAD.APARTMENT
ON RAD.APARTMENT.APART_NUM = RAD.LEASE.APART_NUM
WHERE (RAD.LEASE.LEASE_BEGIN = '2022-07-01' AND RAD.APARTMENT.APART_SQFT > 1000) 
OR (RAD.LEASE.LEASE_BEGIN = '2021-07-01' AND 
	((RAD.APARTMENT.APART_SQFT > 900 AND RAD.LEASE.LEASE_RENT < 1000) OR (RAD.APARTMENT.APART_SQFT > 1000 AND RAD.LEASE.LEASE_RENT < 1100)))
ORDER BY RAD.LEASE.LEASE_BEGIN, RAD.APARTMENT.APART_SQFT, RAD.LEASE.LEASE_RENT;

--5 - Displaying apartment info and the amount for next lase, average rent for all apartments in building, and the difference between the former 2.
-- will only query buildings that have had more htan 3 different apartments that have never been rented. 

SELECT RAD.APARTMENT.APART_BUILDING, RAD.APARTMENT.APART_NUM, RAD.APARTMENT.APART_SQFT, FORMAT(RAD.APARTMENT.APART_RENT, 'C') AS "NEXT LEASE RENT",
  FORMAT(BUILDING_CALC.AVG_RENT, 'C') AS "AVERAGE RENT CHARGED FOR BUILDING",
  FORMAT(RAD.APARTMENT.APART_RENT - BUILDING_CALC.AVG_RENT, 'C') AS "DIFFERENCE"
FROM 
	(SELECT RAD.APARTMENT.APART_BUILDING, AVG(RAD.LEASE.LEASE_RENT) AS AVG_RENT
	FROM RAD.APARTMENT 
	JOIN RAD.LEASE 
	ON RAD.APARTMENT.APART_NUM = RAD.LEASE.APART_NUM
	GROUP BY RAD.APARTMENT.APART_BUILDING
	HAVING COUNT(DISTINCT RAD.APARTMENT.APART_NUM) > 3) AS BUILDING_CALC
JOIN RAD.APARTMENT
ON RAD.APARTMENT.APART_BUILDING = BUILDING_CALC.APART_BUILDING
GROUP BY RAD.APARTMENT.APART_BUILDING, RAD.APARTMENT.APART_NUM, RAD.APARTMENT.APART_SQFT, RAD.APARTMENT.APART_RENT, BUILDING_CALC.AVG_RENT
ORDER BY ROUND(RAD.APARTMENT.APART_RENT - BUILDING_CALC.AVG_RENT,2) , RAD.APARTMENT.APART_NUM;
